export const mimes = {
  imageMimes: [
    "image/bmp",
    "image/gif",
    "image/vnd.microsoft.icon",
    "image/jpeg",
    "image/png",
    "image/apng",
    "image/avif",
    "image/svg+xml",
    "image/tiff",
    "image/webp",
  ],
  imageExt: [
    "bmp",
    "gif",
    "ico",
    "jpeg",
    "jpg",
    "png",
    "svg",
    "tif",
    "webp",
    "avif",
    "apng",
  ],
  pdfMimes: ["application/pdf"],
  pdfExt: ["pdf"],
  documentMimes: [
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "application/vnd.ms-word.document.macroEnabled.12",
    "application/vnd.ms-word.template.macroEnabled.12",
  ],
  documentExt: ["doc", "dot", "docx", "dotx", "docm", "dotm"],
  excelMimes: [
    "text/csv",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    "application/vnd.ms-excel.sheet.macroEnabled.12",
    "application/vnd.ms-excel.template.macroEnabled.12",
    "application/vnd.ms-excel.addin.macroEnabled.12",
    "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
  ],
  excelExt: [
    "csv",
    "xls",
    "xlt",
    "xla",
    "xlsx",
    "xltx",
    "xlsm",
    "xltm",
    "xlam",
    "xlsb",
  ],
  powerPointMimes: [
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.template",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    "application/vnd.ms-powerpoint.addin.macroEnabled.12",
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
  ],
  powerPointExt: [
    "odp",
    "ppt",
    "pot",
    "pps",
    "ppa",
    "pptx",
    "potx",
    "ppsx",
    "ppam",
    "pptm",
    "potm",
    "ppsm",
  ],
  audioMimes: [
    "audio/basic",
    "auido/L24",
    "audio/mid",
    "audio/mpeg",
    "audio/mp4",
    "audio/x-aiff",
    "audio/x-mpegurl",
    "audio/vnd.rn-realaudio",
    "audio/ogg",
    "audio/vorbis",
    "audio/vnd.wav",
    "audio/aac",
    "audio/midi",
    "audio/x-midi",
    "audio/opus",
    "audio/wav",
    "audio/webm",
    "audio/3gpp",
    "audio/3gpp2",
    "application/x-cdf",
  ],
  audioExt: [
    "cds",
    "aac",
    "oga",
    "opus",
    "wave",
    "weba",
    "au",
    "snd",
    "mid",
    "midi",
    "rmi",
    "mp3",
    "mp4",
    "aif",
    "aifc",
    "aiff",
    "m3u",
    "ra",
    "ram",
    "vorbis",
    "wav",
  ],
  textMimes: [
    "text/plain",
    "application/rtf",
    "application/x-sh",
    "application/octet-stream",
    "application/x-csh",
    "application/vnd.oasis.opendocument.text",
  ],
  textExt: ["txt", "rtf", "sh", "bin", "chs", "odt"],
  videoMimes: [
    "video/x-msvideo",
    "video/mpeg",
    "video/ogg",
    "video/mp2t",
    "video/webm",
    "video/3gpp",
    "video/3gpp2",
    "video/mp2t",
  ],
  videoExt: ["mp4", "avi", "mpeg", "ogv", "ts", "webm", "3gp", "3g2"],
  fontsMimes: [
    "application/vnd.ms-fontobject",
    "font/otf",
    "font/ttf",
    "font/woff",
    "font/woff2",
  ],
  fontsExt: ["eot", "otf", "ttf", "woff", "woff2"],
  compressedMimes: [
    "application/x-7z-compressed",
    "application/x-tar",
    "application/vnd.rar",
    "application/x-rar-compressed",
    "application/octet-stream",
    "application/zip",
    "application/x-zip-compressed",
    "multipart/x-zip",
    "multipart/x-bzip",
    "multipart/x-bzip2",
    "application/gzip",
  ],
  compressedExt: ["zip", "rar", ".bz", ".bz2", "gz", "tar", "7z"],
  cssMimes: ["text/css", "text/x-sass", "text/x-scss"],
  cssExt: ["css", "sass", "scss", "styl"],
};
